apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::905418111046:role/eksctl-expense1-nodegroup-expense-NodeInstanceRole-3tKYHHQhXoA6
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::905418111046:user/Harish
      username: Harish      
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-08T02:35:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1293"
  uid: eb8eb22a-212d-4723-a8d7-74d2ece041f0
